### ISSUE TITLE
Pen Robinson

### ISSUE THREAD

**Issue by branch171** [moyner/MultiComponentFlash.jl#11]
Please note the Peng Robinson Coefficients are incorrect

They should be:

# PengRobinson specialization
function static_coefficients(::AbstractPengRobinson)
    return (0.457235529, 0.077796074, 1 + sqrt(2), 1 - sqrt(2))
end

**Comment by moyner** [comment]
Hi, thanks for spotting this. I opted for eight digits accuracy in the code but there was a 7 missing for the second coefficient. I applied your patch in a commit and it will be in the next release: https://github.com/moyner/MultiComponentFlash.jl/commit/b01044328f8cfb5fb51ed895b2e695995ce902fe
